### ISSUE TITLE
Items not going into bank or being pulled from bank when clicking a set.

### ISSUE THREAD

**Issue by Immodium** [Rottenbeer/ItemRack#266]
Before cata pre-patch I was able to go to the bank and pull out or toss in a set depending on which one I clicked.  Now when I do that nothing happens.

I looked through the issues logs and didn't see a fix for it?  Sorry if this a duplicate, but I would like to know how to fix it.

**Comment by justmuddgaming** [comment]
+1 to this happening to me in cata

**Comment by Xdembe** [comment]
https://github.com/Rottenbeer/ItemRack/blob/e2c84c2b5d2d0944f379c13e074df0caef9912d0/ItemRack/ItemRack.lua#L122
change this line to
`elseif ItemRack.IsBCC() or ItemRack.IsWrath() or ItemRack.IsCata() then
`

**Comment by Immodium** [comment]
> https://github.com/Rottenbeer/ItemRack/blob/e2c84c2b5d2d0944f379c13e074df0caef9912d0/ItemRack/ItemRack.lua#L122
> 
> 
> change this line to
> `elseif ItemRack.IsBCC() or ItemRack.IsWrath() or ItemRack.IsCata() then `

That worked, thank you!

**Comment by Rottenbeer** [comment]
Should be fixed by https://github.com/Rottenbeer/ItemRack/pull/277

**Comment by trying-to-function** [comment]
@Rottenbeer this is still not working on Season of Discovery.

**Comment by trying-to-function** [comment]
Additionally, this is the error that is being thrown:

```lua
69x ItemRack/ItemRack.lua:43: bad argument #1 to 'IsInventorySlotEngravable' (outside of expected range 0 to 4294967295 - Usage: local result = C_Engraving.IsInventorySlotEngravable(containerIndex, slotIndex))
[string "=[C]"]: in function `IsInventorySlotEngravable'
[string "@ItemRack/ItemRack.lua"]:43: in function `AppendRuneID'
[string "@ItemRack/ItemRack.lua"]:709: in function `getid'
[string "@ItemRack/ItemRack.lua"]:822: in function `FindInBank'
[string "@ItemRack/ItemRack.lua"]:2180: in function `MissingItems'
[string "@ItemRack/ItemRack.lua"]:1264: in function `BuildMenu'
[string "@ItemRack/ItemRack.lua"]:1920: in function `OnClick'
[string "@BugSack/Libs/LibDBIcon-1.0-55/LibDBIcon-1.0.lua"]:179: in function <BugSack/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:177>

Locals:
(*temporary) = -1
(*temporary) = 1
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local result = C_Engraving.IsInventorySlotEngravable(containerIndex, slotIndex)"
```

**Comment by trying-to-function** [comment]
Did further research and found https://github.com/arkayenro/arkinventory/issues/2019. I am not sure this is the correct fix, but I changed line 36 of `ItemRack.lua` to `return C_Engraving and blizzard_id ~= nil and C_Engraving.IsEngravingEnabled()` and it seems to work.

See also:
https://us.forums.blizzard.com/en/wow/t/sod-engraved-items-in-the-bank-isinventoryslotengravable-bug/1964618

You can look at the git changes arkayenro did to fix the issue: [ArkInventory-3.11.01-alpha-7-with-git-changes-from-6.zip](https://github.com/user-attachments/files/17176194/ArkInventory-3.11.01-alpha-7-with-git-changes-from-6.zip)
